server:
  port: 8085
spring:
  application:
    name: "BASICDATA"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=172.30.23.136;databaseName=way;encrypt=true;trustServerCertificate=true;
    username: sa
    password: asd123!@#
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false

eureka:
#  baseServerUrl: 192.168.100.10
    baseServerUrl: localhost
  client:
    service-url:
      defaultZone: http://${eureka.baseServerUrl}:8080/eureka


PageRequest :
  page : 0
  size : 10

springdoc:
  swagger-ui:
    path: index.html
    server-url: http://localhost:8083
#    server-url: http://ctiran.ir
    enabled: true
    config-url: /basicDataSwagger/v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /basicDataSwagger/v3/api-docs

redis:
  port: 63799
#  port: 6379
  size: 512mb
  root-package-name: org.basicData.model