server:
  port: 8084
spring:
  application:
    name: "BASICDATA"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=localhost;databaseName=way;encrypt=true;trustServerCertificate=true;
    username: sa
    password: asd123!@#
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
